== Classes overview

This project contains 3 classes and 0 interface.

.Classes list
[cols="", %autowidth, frame=all, grid=all, stripes=none]
|===
|Classes |Interfaces

|<<Log Event Msg.lvclass>>
|

|<<Alpha Task Msg.lvclass>>
|

|<<Beta Task Msg.lvclass>>
|
|===

[plantuml, format="svg", align="center"]
....
@startuml
set namespaceSeparator :
skinparam ClassBackgroundColor #FFFFFF
skinparam ClassBorderColor #555555
skinparam ClassFontColor #000000
skinparam ClassHeaderBackgroundColor #808080

skinparam top to bottom direction
class "CI Tests.lvlib:Log Event Msg" {
{field} -Event Text : String
{static} {method} +Send Log Event()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "CI Tests.lvlib:Log Event Msg"


class "Alpha Actor.lvlib:Alpha Task Msg" {
{field} +Data : I32
{static} {method} +Send Alpha Task()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "Alpha Actor.lvlib:Alpha Task Msg"


class "Beta Actor.lvlib:Beta Task Msg" {
{field} -Data : I32
{static} {method} +Send Beta Task()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "Beta Actor.lvlib:Beta Task Msg"



@enduml
....
